language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - export TZ=Asia/Jakarta
  - npm install -g npm@latest
install:
  - npm install --only=dev
script:
  - npm test
after_success: npm run coverage