language: node_js
node_js:
  - "node"
  - "14"
  - "12"
  - "10"
env:
  global:
    - NODE_ENV=development
before_install:
  - export TZ=Asia/Jakarta
install:
  - npm install
script:
  - npm test
after_success: npm run coverage
