language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
env:
  global:
    - NODE_ENV=development
before_install:
  - export TZ=Asia/Jakarta
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm test
after_success: npm run coverage